linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gofmt
    - goprintffuncname
    - gosec
    - loggercheck
    - makezero
    - mirror
    - musttag
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - goprintffuncname
    - usestdlibvars
    - zerologlint
    - gocritic
    - misspell
    - gofumpt
    - contextcheck # XXX may need //nolint sometimes
    - nilerr # XXX may need //nolint sometimes
    # - errcheck        # REASON: prohibits unchecked error in defer, won't use unless fixed
    # - ireturn         # REASON: won't allow to return something like pgx.Row (see involta-go-packages/database)
    # - wsl             # REASON: emits too many controversial warnings
    # - forcetypeassert # REASON: sometimes the only thing is to panic if assertion goes wrong
    - importas
  disable: []
  presets: []
  fast: true

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    check-shadowing: false
    shadow: false
    disable:
      - fieldalignment
  errchkjson:
    check-error-free-encoding: true
  revive:
    enable-all-rules: false
    rules:
      - name: "error-return"
      - name: "increment-decrement"
        disabled: true
      - name: "indent-error-flow"
      - name: "struct-tag"
        arguments: ["json,inline", "bson,outline,gnu"]
      - name: "constant-logical-expr"
      - name: "bool-literal-in-expr"
      - name: "waitgroup-by-value"
      - name: "atomic"
      - name: "unused-receiver"
      - name: "unconditional-recursion"
      - name: "defer"
      - name: "datarace"
      # should force devs make more files inside a package (hecking structs.go)
      - name: "max-public-structs"
        arguments: [7]
      - name: "empty-lines"
  importas:
    # Do not allow unaliased imports of aliased packages.
    no-unaliased: true
    alias:
      - pkg: git.devolta.ru/involta-go-packages/bonuses(/v[\w\d]+)?
        alias: bonuses
      - pkg: git.devolta.ru/involta-go-packages/bonuses(/v[\w\d]+)?/repo
        alias: bonuses_repo
      - pkg: git.devolta.ru/involta-go-packages/bonuses/pkg/date_utils
        alias: date_utils
      - pkg: git.devolta.ru/involta-go-packages/cache(/v[\w\d]+)?
        alias: cache
      - pkg: git.devolta.ru/involta-go-packages/currencies(/v[\w\d]+)?
        alias: currencies
      - pkg: git.devolta.ru/involta-go-packages/database(/v[\w\d]+)?/mongo
        alias: database_mongo
      - pkg: git.devolta.ru/involta-go-packages/database(/v[\w\d]+)?/postgres
        alias: database_pg
      - pkg: git.devolta.ru/involta-go-packages/errors(/v[\w\d]+)?
        alias: errorx
      - pkg: git.devolta.ru/involta-go-packages/healthcheck(/v[\w\d]+)?
        alias: healthcheck
      - pkg: git.devolta.ru/involta-go-packages/message-queue(/v[\w\d]+)?
        alias: message_queue
      - pkg: git.devolta.ru/involta-go-packages/message-queue(/v[\w\d]+)?/config
        alias: message_queue_config
      - pkg: git.devolta.ru/involta-go-packages/middleware(/v[\w\d]+)?
        alias: middleware
      - pkg: git.devolta.ru/involta-go-packages/payments(/v[\w\d]+)?
        alias: payments
      - pkg: git.devolta.ru/involta-go-packages/payments(/v[\w\d]+)?/bills
        alias: payments_bills
      - pkg: git.devolta.ru/involta-go-packages/payments(/v[\w\d]+)?/sber
        alias: payments_sber
      - pkg: git.devolta.ru/involta-go-packages/payments(/v[\w\d]+)?/yookassa
        alias: payments_yookassa
      - pkg: git.devolta.ru/involta-go-packages/products(/v[\w\d]+)?
        alias: products
      - pkg: git.devolta.ru/involta-go-packages/products(/v[\w\d]+)?/structs
        alias: products_st
      - pkg: git.devolta.ru/involta-go-packages/products(/v[\w\d]+)?/tags
        alias: products_tags
      - pkg: git.devolta.ru/involta-go-packages/reindexer(/v[\w\d]+)?
        alias: reindexerx
      - pkg: git.devolta.ru/involta-go-packages/remote-config(/v[\w\d]+)?
        alias: remote_config
      - pkg: git.devolta.ru/involta-go-packages/remote-config(/v[\w\d]+)?/micro_config
        alias: micro_config
      - pkg: git.devolta.ru/involta-go-packages/roles(/v[\w\d]+)?
        alias: roles
      - pkg: git.devolta.ru/involta-go-packages/sites(/v[\w\d]+)?
        alias: sites
      - pkg: git.devolta.ru/involta-go-packages/telemetry(/v[\w\d]+)?
        alias: telemetry
      - pkg: github.com/restream/reindexer(/v[\w\d]+)?
        alias: reindexer
      - pkg: github.com/swaggo/http-swagger
        alias: http_swagger
